<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="snake_joint">

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="MASS_1" value="0.75" />
    <xacro:property name="HEIGHT_1" value="0.1" />
    <xacro:property name="WIDTH_1" value="1" />
    <xacro:property name="BREADTH_1" value="1" />
    <xacro:property name="BASE_ORIGIN_X" value="0" />
    <xacro:property name="BASE_ORIGIN_Y" value="0" />
    <xacro:property name="BASE_ORIGIN_Z" value="${HEIGHT_1 / 2}" />

    <xacro:property name="MASS_2" value="0.10" />
    <xacro:property name="HEIGHT_2" value="0.1" />
    <xacro:property name="WIDTH_2" value="0.1" />
    <xacro:property name="BREADTH_2" value="0.1" />

    <xacro:property name="MASS_3" value="0.15" />
    <xacro:property name="RADIUS_3" value="0.15" />
    <xacro:property name="LENGTH_3" value="0.10" />

    <xacro:property name="MASS_4" value="1.0" />
    <xacro:property name="RADIUS_4" value="0.10" />
    <xacro:property name="LENGTH_4" value="0.40" />

    <xacro:property name="MASS_5" value="0.25" />
    <xacro:property name="RADIUS_5" value="0.10" />
    <xacro:property name="LENGTH_5" value="0.20" />

    <link name="base_link_rotation">
        <visual>
            <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${BASE_ORIGIN_Z}" rpy="0 0 0"/>
            <geometry>
                <box size="${WIDTH_1} ${BREADTH_1} ${HEIGHT_1}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${BASE_ORIGIN_Z}" rpy="0 0 0"/>
            <geometry>
                <box size="${WIDTH_1} ${BREADTH_1} ${HEIGHT_1}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${BASE_ORIGIN_Z}" rpy="0 0 0"/>
            <mass value="${MASS_1}"/>
            <inertia ixx="${MASS_1 / 6.0 * (WIDTH_1 * WIDTH_1 + HEIGHT_1 * HEIGHT_1)}" ixy="0.0" ixz="0.0"
                     iyy="${MASS_1 / 6.0 * (HEIGHT_1 * HEIGHT_1 + WIDTH_1 * WIDTH_1)}" iyz="0.0"
                     izz="${MASS_1 / 6.0 * (WIDTH_1 * WIDTH_1 + WIDTH_1 * WIDTH_1)}"/>
        </inertial>
    </link>


    <link name="fixated_link">
        <visual>
            <origin xyz="0 0 ${LENGTH_4 / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${LENGTH_4 / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${LENGTH_4 / 2}" rpy="0 0 0" />
            <mass value="${MASS_2}"/>
            <inertia ixx="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" iyz="0.0"
                     izz="${(MASS_2 * (RADIUS_4 * RADIUS_4)) / 2}"/>
        </inertial>
    </link>

    <link name="pivot">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${MASS_3}"/>
            <inertia ixx="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" iyz="0.0"
                     izz="${(MASS_3 * (RADIUS_5 * RADIUS_5)) / 2}"/>
        </inertial>
    </link>

    <link name="moving_link">
        <visual>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <mass value="${MASS_2}"/>
            <inertia ixx="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" iyz="0.0"
                     izz="${(MASS_2 * (RADIUS_4 * RADIUS_4)) / 2}"/>
        </inertial>
    </link>

    <!--add a phantom of the moving link to display the desired position-->
    <!--
    <link name="pivot_phantom">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${MASS_3}"/>
            <inertia ixx="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" iyz="0.0"
                     izz="${(MASS_3 * (RADIUS_5 * RADIUS_5)) / 2}"/>
        </inertial>
    </link>

    <link name="moving_link_phantom">
        <inertial>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <mass value= "1.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0"
                     iyy="0.0" iyz="0.0"
                     izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
            <material name="MyGreen">
                <ambient>0 1 0 1</ambient>
                <diffuse>0 1 0 1</diffuse>
                <color rgba="0 1.0 0.5 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="100000 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </collision>
    </link>
-->
    <joint name="world_to_base" type="fixed">
        <parent link="world"/>
        <child link="base_link_rotation"/>
    </joint>

    <joint name="base_to_fixated" type="fixed">
        <parent link="base_link_rotation"/>
        <child link="fixated_link"/>
    </joint>

    <joint name="fixated_to_pivot" type="revolute">
        <parent link="fixated_link" />
        <child link="pivot" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 ${LENGTH_4}" rpy="0 -${M_PI / 2} 0"/>
        <dynamics damping="1"/>
        <limit effort="1000.0" lower="${-M_PI / 2}" upper="${M_PI / 2}" velocity="1.0" />
    </joint>
    
    <joint name="pivot_to_moving_link" type="fixed">
        <parent link="pivot" />
        <child link="moving_link" />
        <!--
        <axis xyz="0 0 1" />
        <origin xyz="0 0 0" />
        <dynamics damping="1"/>
        <limit effort="10" lower="-0.4" upper="0.4" velocity="1" />
        -->
    </joint>

    <!--add a phantom of the moving link to display the desired position
    <joint name="fixated_to_pivot_phantom" type="revolute">
        <parent link="fixated_link" />
        <child link="pivot_phantom" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 ${LENGTH_4}" rpy="0 -${M_PI / 2} 0"/>
        <limit effort="1000.0" lower="${-M_PI / 2}" upper="${M_PI / 2}" velocity="1.0" />
    </joint>

    <joint name="pivot_to_moving_link_phantom" type="revolute">
        <parent link="pivot_phantom" />
        <child link="moving_link_phantom" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 0" />
        <dynamics damping="100"/>
        <limit effort="10" lower="-0.4" upper="0.4" velocity="1" />
    </joint>
    -->
    

    <transmission name="motor_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="fixated_to_pivot">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <!--
    <transmission name="spring_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="pivot_to_moving_link">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="spring">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
-->
<!--Added for phantom-->
<!--
    <transmission name="motor_tran_phantom">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="fixated_to_pivot_phantom">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_phantom">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="spring_tran_phantom">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="pivot_to_moving_link_phantom">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="spring_phantom">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
-->



</robot>
