<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sea_demo">

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="MASS_1" value="0.75" />
    <xacro:property name="HEIGHT_1" value="0.1" />
    <xacro:property name="WIDTH_1" value="1" />
    <xacro:property name="BREADTH_1" value="1" />
    <xacro:property name="BASE_ORIGIN_X" value="0" />
    <xacro:property name="BASE_ORIGIN_Y" value="0" />
    <xacro:property name="BASE_ORIGIN_Z" value="${HEIGHT_1 / 2}" />

    <xacro:property name="MASS_2" value="0.10" />
    <xacro:property name="HEIGHT_2" value="0.1" />
    <xacro:property name="WIDTH_2" value="0.1" />
    <xacro:property name="BREADTH_2" value="0.1" />

    <xacro:property name="MASS_3" value="0.15" />
    <xacro:property name="RADIUS_3" value="0.15" />
    <xacro:property name="LENGTH_3" value="0.10" />

    <xacro:property name="MASS_4" value="1.0" />
    <xacro:property name="RADIUS_4" value="0.10" />
    <xacro:property name="LENGTH_4" value="0.40" />

    <xacro:property name="MASS_5" value="0.25" />
    <xacro:property name="RADIUS_5" value="0.10" />
    <xacro:property name="LENGTH_5" value="0.20" />

    <link name="base_link_rotation">
        <visual>
            <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${BASE_ORIGIN_Z}" rpy="0 0 0"/>
            <geometry>
                <box size="${WIDTH_1} ${BREADTH_1} ${HEIGHT_1}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${BASE_ORIGIN_Z}" rpy="0 0 0"/>
            <geometry>
                <box size="${WIDTH_1} ${BREADTH_1} ${HEIGHT_1}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${BASE_ORIGIN_Z}" rpy="0 0 0"/>
            <mass value="${MASS_1}"/>
            <inertia ixx="${MASS_1 / 6.0 * (WIDTH_1 * WIDTH_1 + HEIGHT_1 * HEIGHT_1)}" ixy="0.0" ixz="0.0"
                     iyy="${MASS_1 / 6.0 * (HEIGHT_1 * HEIGHT_1 + WIDTH_1 * WIDTH_1)}" iyz="0.0"
                     izz="${MASS_1 / 6.0 * (WIDTH_1 * WIDTH_1 + WIDTH_1 * WIDTH_1)}"/>
        </inertial>
    </link>
    <!--
    <link name="link_1_rot_in">
        <visual>
            <origin xyz="0 0 -${LENGTH_3 / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_3}" length="${LENGTH_3}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 -${LENGTH_3 / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_3}" length="${LENGTH_3}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 -${LENGTH_3 / 2}" rpy="0 0 0" />
            <mass value="${MASS_3}"/>
            <inertia ixx="${((MASS_3 * (LENGTH_3 * LENGTH_3)) / 12) + (MASS_3 * (RADIUS_3 * RADIUS_3)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_3 * (LENGTH_3 * LENGTH_3)) / 12) + (MASS_3 * (RADIUS_3 * RADIUS_3)) / 4}" iyz="0.0"
                     izz="${(MASS_3 * (RADIUS_3 * RADIUS_3)) / 2}"/>
        </inertial>
    </link>
    -->

    <link name="link_1_rot_out">
        <visual>
            <origin xyz="0 0 ${LENGTH_4 / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${LENGTH_4 / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${LENGTH_4 / 2}" rpy="0 0 0" />
            <mass value="${MASS_2}"/>
            <inertia ixx="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" iyz="0.0"
                     izz="${(MASS_2 * (RADIUS_4 * RADIUS_4)) / 2}"/>
        </inertial>
    </link>

    <link name="link_2_rot_in">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${MASS_3}"/>
            <inertia ixx="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" iyz="0.0"
                     izz="${(MASS_3 * (RADIUS_5 * RADIUS_5)) / 2}"/>
        </inertial>
    </link>

    <link name="link_2_rot_out">
        <visual>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <mass value="${MASS_2}"/>
            <inertia ixx="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" iyz="0.0"
                     izz="${(MASS_2 * (RADIUS_4 * RADIUS_4)) / 2}"/>
        </inertial>
    </link>
    <!--
    <link name="link_3_rot_in">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI / 2}" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI / 2}" />
            <geometry>
                <cylinder radius="${RADIUS_5}" length="${LENGTH_5}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI / 2}" />
            <mass value="${MASS_3}"/>
            <inertia ixx="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_3 * (LENGTH_5 * LENGTH_5)) / 12) + (MASS_3 * (RADIUS_5 * RADIUS_5)) / 4}" iyz="0.0"
                     izz="${(MASS_3 * (RADIUS_5 * RADIUS_5)) / 2}"/>
        </inertial>
    </link>

    <link name="link_3_rot_out">
        <visual>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <geometry>
                <cylinder radius="${RADIUS_4}" length="${LENGTH_4}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${(LENGTH_4 / 2) + (RADIUS_5 / 2)} 0 0" rpy="0 ${M_PI / 2} 0" />
            <mass value="${MASS_2}"/>
            <inertia ixx="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" ixy="0.0" ixz="0.0"
                     iyy="${((MASS_2 * (LENGTH_4 * LENGTH_4)) / 12) + (MASS_2 * (RADIUS_4 * RADIUS_4)) / 4}" iyz="0.0"
                     izz="${(MASS_2 * (RADIUS_4 * RADIUS_4)) / 2}"/>
        </inertial>
    </link>

    <link name="end_effector">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.05 0.1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.05 0.1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.5"/>
            <inertia ixx="0" ixy="0.0" ixz="0.0"
                     iyy="0" iyz="0.0"
                     izz="0"/>
        </inertial>
    </link>
    -->
    <joint name="fixed_rotation" type="fixed">
        <parent link="world"/>
        <child link="base_link_rotation"/>
    </joint>

    <joint name="link_1_fixed" type="fixed">
        <parent link="base_link_rotation"/>
        <child link="link_1_rot_out"/>
    </joint>
<!--
    <joint name="link_1_motor" type="revolute">
        <parent link="base_link_rotation" />
        <child link="link_1_rot_in" />
        <axis xyz="0 0 1" />
        <origin xyz="${BASE_ORIGIN_X} ${BASE_ORIGIN_Y} ${HEIGHT_1 * 2}" rpy="0 0 ${M_PI / 2}"/>
        <limit effort="1000" lower="${-M_PI / 2}" upper="${M_PI / 2}" velocity="1" />
    </joint>

    <joint name="link_1_spring" type="revolute">
        <parent link="link_1_rot_in" />
        <child link="link_1_rot_out" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 0" />
        <dynamics damping="0.2"/>
        <limit effort="10" lower="-0.4" upper="0.4" velocity="1" />
    </joint>
-->
    <joint name="link_2_motor" type="revolute">
        <parent link="link_1_rot_out" />
        <child link="link_2_rot_in" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 ${LENGTH_4}" rpy="0 -${M_PI / 2} 0"/>
        <limit effort="1000.0" lower="${-M_PI / 2}" upper="${M_PI / 2}" velocity="1.0" />
    </joint>

    <joint name="link_2_spring" type="revolute">
        <parent link="link_2_rot_in" />
        <child link="link_2_rot_out" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 0" />
        <dynamics damping="1"/>
        <limit effort="10" lower="-0.4" upper="0.4" velocity="1" />
    </joint>
    <!--
    <joint name="link_3_motor" type="revolute">
        <parent link="link_2_rot_out" />
        <child link="link_3_rot_in" />
        <axis xyz="0 0 1" />
        <origin xyz="${LENGTH_4 + (RADIUS_3 / 2)} 0 0" />
        <limit effort="1000" lower="${-M_PI / 2}" upper="${M_PI / 2}" velocity="1.0" />
    </joint>

    <joint name="link_3_spring" type="revolute">
        <parent link="link_3_rot_in" />
        <child link="link_3_rot_out" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0 0" />
        <dynamics damping="0.2"/>
        <limit effort="10" lower="-0.4" upper="0.4" velocity="1" />
    </joint>

    <joint name="ee_joint" type="revolute">
        <parent link="link_3_rot_out"/>
        <child link="end_effector"/>
        <origin xyz="${(LENGTH_4) + 0.075} 0 0" rpy="0 0 ${M_PI / 2}"/>
        <limit effort="10" lower="0" upper="0" velocity="1" />
    </joint>
    -->
    <!-- <transmission name="motor_1_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_1_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission> -->

    <!-- <transmission name="spring_1_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_1_spring">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="spring_1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission> -->

    <transmission name="motor_2_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_2_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="spring_2_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_2_spring">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="spring_2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <!--
    <transmission name="motor_3_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_3_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_3">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="spring_3_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link_3_spring">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="spring_3">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    -->
</robot>
